logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
server:
  address: 0.0.0.0
  port: 5000
spring:
  threads:
    virtual:
      enabled: true
example:
  app:
    jwtSecret: ======================12345678=Spring===========================
    jwtExpirationMs: 86400000